DBusException: override both __str__ and __unicode__
Avoid chaining up to the superclass, because that behaves particularly
oddly. This fixes regression test failures: str(some_dbus_exception) was no
longer prefixed with the D-Bus error name under Python 2.

Bug: https://bugs.freedesktop.org/show_bug.cgi?id=55899